# @doc https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: github-actions-artillery
description: Get started with Container actions
author: kenju
inputs:
  target:
    required: true
    default: https://kenju.netlify.com/
  duration:
    required: false
    default: 10 #sec
  arrivalRate:
    required: false
    default: 1
runs:
  using: docker
  image: Dockerfile
# Feather (https://feathericons.com/) icon
branding:
  icon: zap
  color: orange
