# GitHub Actions metadata file
#
# @doc https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
#
name: github-actions-artillery
author: kenju
description: Load test your application with artillery/artillery
inputs:
  target:
    required: true
  duration:
    required: false
    default: 10 #sec
  arrivalRate:
    required: false
    default: 1
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}
    - ${{ inputs.duration }}
    - ${{ inputs.arrivalRate }}
branding: # Feather (https://feathericons.com/) icon
  icon: zap
  color: orange
