on: [push]

jobs:
  load-test-sample:
    runs-on: ubuntu-latest
    name: A load test sample job
    steps:
    - uses: actions/checkout@master
    - run: ls -la $GITHUB_WORKSPACE
    - name: Load Test action step
      id: load-test
      uses: kenju/github-actions-artillery@master
      with:
        filepath: load-test.yml
